# Generated by Django 2.2.11 on 2020-05-29 20:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskDetails',
            fields=[
                ('TaskId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taskName', models.TextField()),
                ('taskDescription', models.TextField()),
                ('taskCategory', models.CharField(max_length=100)),
                ('taskSubCategory', models.CharField(max_length=100)),
                ('taskAttachment1', models.URLField()),
                ('taskAttachment2', models.URLField()),
                ('taskStatus', models.CharField(max_length=100)),
                ('creationTime', models.DateTimeField(default=datetime.datetime(2020, 5, 29, 20, 5, 10, 481788, tzinfo=utc))),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkypeId', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSolutions',
            fields=[
                ('solutionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solutionDescription', models.TextField()),
                ('solAttachment1', models.UUIDField()),
                ('solAttachment2', models.UUIDField()),
                ('creationTime', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custws.UserTaskDetails')),
            ],
        ),
    ]
