# Generated by Django 2.2.11 on 2020-06-02 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custws', '0002_auto_20200530_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksolutions',
            name='solAttachment1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tasksolutions',
            name='solAttachment2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 10, 48, 868827, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('MobileNo', models.IntegerField(max_length=20)),
                ('houseNo', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField(max_length=50)),
                ('messenger', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
