# Generated by Django 2.2.11 on 2020-06-04 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0005_auto_20200603_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdetails',
            name='currency',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 16, 55, 19, 428391, tzinfo=utc)),
        ),
    ]
