# Generated by Django 2.2.11 on 2020-06-04 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0007_auto_20200604_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdetails',
            name='custTaskId',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 20, 7, 26, 561311, tzinfo=utc)),
        ),
    ]
