# Generated by Django 2.2.11 on 2020-06-04 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0008_auto_20200605_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskdetails',
            name='custTaskId',
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 20, 9, 7, 775863, tzinfo=utc)),
        ),
    ]
