# Generated by Django 2.2.11 on 2020-06-04 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0009_auto_20200605_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdetails',
            name='custTaskId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 20, 11, 17, 478514, tzinfo=utc)),
        ),
    ]
