# Generated by Django 2.2.11 on 2020-06-05 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0010_auto_20200605_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 6, 13, 30, 799030, tzinfo=utc)),
        ),
    ]
