# Generated by Django 2.2.11 on 2020-06-05 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custws', '0011_auto_20200605_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskdetails',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertaskdetails',
            name='creationTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 18, 26, 47, 348514, tzinfo=utc)),
        ),
    ]
